#ifndef SCREEN_CONFIG_H
#define SCREEN_CONFIG_H

// Main Window Parameters
#define SCREEN_WIDTH 1600
#define SCREEN_HEIGHT 1200
#define SCREEN_TITLE "TETRIS"
#define SCREEN_BG_COLOR BLACK

// Tetris Grid Parameters
#define GRID_WIDTH 10
#define GRID_HEIGHT 20
#define GRID_SIZE (GRID_WIDTH * (GRID_HEIGHT + 1))

#define BLOCK_SIZE (TSCREEN_HEIGHT / GRID_HEIGHT)
#define BLOCK_COLOR WHITE

// Tetris Screen Parameters
#define TSCREEN_POSX 200
#define TSCREEN_POSY 100
#define TSCREEN_WIDTH (GRID_WIDTH * BLOCK_SIZE)
#define TSCREEN_HEIGHT 1000
#define TSCREEN_COLOR BLACK

#define T_BORDER_COLOR WHITE
#define T_BORDER_THICK 6

#endif // SCREEN_CONFIG_H
