// Main Window Parameters
#define SCREEN_WIDTH 1600
#define SCREEN_HEIGHT 1200
#define SCREEN_TITLE "TETRIS"
#define SCREEN_BG_COLOR BEIGE

// Tetris Screen Parameters
#define TSCREEN_POSX 200
#define TSCREEN_POSY 100
#define TSCREEN_WIDTH 600
#define TSCREEN_HEIGHT 1000
#define TSCREEN_COLOR BLACK

#define T_BORDER_COLOR WHITE
#define T_BORDER_THICK 10
